5# Note: all properties defined in this file are subject to replacement by the configuration server.
spring:
  application:
    name: subject
---
server:
  port: ${vcap.application.port:8081}
---
words: fallback

 
