# Properties active for ALL profiles:
spring:
  application:
    name: configserver
---
server:
  port: ${vcap.application.port:8888}
---
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bipingupta/Microservices-Demo
          searchPaths: ConfigData

       
