# Properties active for ALL profiles:
---
server:
  port: 9192
---
spring:
  application:
    name: oauth2client
---
eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${SERVER_IP:localhost}:8761/eureka/
---      
security: 
  oauth2:
    client:
      clientId: client
      clientSecret: secret
      userAuthorizationUri: http://localhost:9191/oauth2server/oauth/authorize
      accessTokenUri: http://localhost:9191/oauth2server/oauth/token
    resource:
      tokenInfoUri: http://localhost:9191/oauth2server/oauth/check_token     
  basic:
    enabled: false
---
spring:
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
      
      