spring:
  application:
    name: eurekaserver

server:
  port: ${vcap.application.port:8761}
  
eureka:

  client:
    registerWithEureka: true
    fetchRegistry: false
    service-url:
      defaultZone: ${vcap.services.eureka.credentials.url:https://eureka007.cfapps.io/eureka/}
      
  server:
    waitTimeInMsWhenSyncEmpty: 0

  instance:
    nonSecurePort: 80
    hostname: ${vcap.application.uris[0]}
    metadataMap:
      instanceId: ${vcap.application.instance_id}
#      instanceId: ${vcap.application.name}:${vcap.application.instance_id:${vcap.application.port}}